services:
  service1:
    container_name: "CED"
    image: "node:latest"
    volumes:
      - "volume1:/data"
  service2:
    container_name: "PIZDA"
    image: "mysql"
    volumes:
      - "./cartella:/data"
    environment:
      - MYSQL_ROOT_PASSWORD=cisco

volumes:
  volume1: